// Code generated by protocol.py DO NOT EDIT
// Generator can be found at https://github.com/FlowingSPDG/go-obs-websocket/blob/master/codegen/protocol.py

package obsws

// SwitchScenesEvent : Indicates a scene change.
//
// Since obs-websocket version: 0.3.
//
// https://github.com/Palakis/obs-websocket/blob/4.x-current/docs/generated/protocol.md#switchscenes
type SwitchScenesEvent struct {
	// The new scene.
	// Required: Yes.
	SceneName string `json:"scene-name,omitempty"`
	// List of scene items in the new scene.
	// Same specification as [`GetCurrentScene`](#getcurrentscene).
	// Required: Yes.
	Sources []*SceneItem `json:"sources,omitempty"`
	_event  `json:",squash"`
}

// ScenesChangedEvent :
//
// Note: This event is not fired when the scenes are reordered.
//
// Since obs-websocket version: 0.3.
//
// https://github.com/Palakis/obs-websocket/blob/4.x-current/docs/generated/protocol.md#sceneschanged
type ScenesChangedEvent struct {
	// Scenes list.
	// Required: Yes.
	Scenes []*Scene `json:"scenes,omitempty"`
	_event `json:",squash"`
}

// SceneCollectionChangedEvent : Triggered when switching to another scene collection or when renaming the current scene collection.
//
// Since obs-websocket version: 4.0.0.
//
// https://github.com/Palakis/obs-websocket/blob/4.x-current/docs/generated/protocol.md#scenecollectionchanged
type SceneCollectionChangedEvent struct {
	// Name of the new current scene collection.
	// Required: Yes.
	SceneCollection string `json:"sceneCollection,omitempty"`
	_event          `json:",squash"`
}

// SceneCollectionListChangedEvent : Triggered when a scene collection is created, added, renamed, or removed.
//
// Since obs-websocket version: 4.0.0.
//
// https://github.com/Palakis/obs-websocket/blob/4.x-current/docs/generated/protocol.md#scenecollectionlistchanged
type SceneCollectionListChangedEvent struct {
	// Scene collections list.
	// Required: Yes.
	SceneCollections []map[string]interface{} `json:"sceneCollections,omitempty"`
	// Scene collection name.
	// Required: Yes.
	SceneCollectionsName string `json:"sceneCollections.*.name,omitempty"`
	_event               `json:",squash"`
}
