// Code generated by protocol.py DO NOT EDIT
// Generator can be found at https://github.com/FlowingSPDG/go-obs-websocket/blob/master/codegen/protocol.py

package obsws

// SourceCreatedEvent : A source has been created
// A source can be an input, a scene or a transition.
//
// Since obs-websocket version: 4.6.0.
//
// https://github.com/Palakis/obs-websocket/blob/4.x-current/docs/generated/protocol.md#sourcecreated
type SourceCreatedEvent struct {
	// Source name.
	// Required: Yes.
	SourceName string `json:"sourceName,omitempty"`
	// Source type.
	// Can be "input", "scene", "transition" or "filter".
	// Required: Yes.
	SourceType string `json:"sourceType,omitempty"`
	// Source kind.
	// Required: Yes.
	SourceKind string `json:"sourceKind,omitempty"`
	// Source settings.
	// Required: Yes.
	SourceSettings map[string]interface{} `json:"sourceSettings,omitempty"`
	_event         `json:",squash"`
}

// SourceDestroyedEvent : A source has been destroyed/removed
// A source can be an input, a scene or a transition.
//
// Since obs-websocket version: 4.6.0.
//
// https://github.com/Palakis/obs-websocket/blob/4.x-current/docs/generated/protocol.md#sourcedestroyed
type SourceDestroyedEvent struct {
	// Source name.
	// Required: Yes.
	SourceName string `json:"sourceName,omitempty"`
	// Source type.
	// Can be "input", "scene", "transition" or "filter".
	// Required: Yes.
	SourceType string `json:"sourceType,omitempty"`
	// Source kind.
	// Required: Yes.
	SourceKind string `json:"sourceKind,omitempty"`
	_event     `json:",squash"`
}

// SourceVolumeChangedEvent : The volume of a source has changed.
//
// Since obs-websocket version: 4.6.0.
//
// https://github.com/Palakis/obs-websocket/blob/4.x-current/docs/generated/protocol.md#sourcevolumechanged
type SourceVolumeChangedEvent struct {
	// Source name.
	// Required: Yes.
	SourceName string `json:"sourceName,omitempty"`
	// Source volume.
	// Required: Yes.
	Volume float64 `json:"volume,omitempty"`
	// Source volume in Decibel.
	// Required: Yes.
	VolumeDb float64 `json:"volumeDb,omitempty"`
	_event   `json:",squash"`
}

// SourceMuteStateChangedEvent : A source has been muted or unmuted.
//
// Since obs-websocket version: 4.6.0.
//
// https://github.com/Palakis/obs-websocket/blob/4.x-current/docs/generated/protocol.md#sourcemutestatechanged
type SourceMuteStateChangedEvent struct {
	// Source name.
	// Required: Yes.
	SourceName string `json:"sourceName,omitempty"`
	// Mute status of the source.
	// Required: Yes.
	Muted  bool `json:"muted,omitempty"`
	_event `json:",squash"`
}

// SourceAudioDeactivatedEvent : A source has removed audio.
//
// Since obs-websocket version: 4.9.0.
//
// https://github.com/Palakis/obs-websocket/blob/4.x-current/docs/generated/protocol.md#sourceaudiodeactivated
type SourceAudioDeactivatedEvent struct {
	// Source name.
	// Required: Yes.
	SourceName string `json:"sourceName,omitempty"`
	_event     `json:",squash"`
}

// SourceAudioActivatedEvent : A source has added audio.
//
// Since obs-websocket version: 4.9.0.
//
// https://github.com/Palakis/obs-websocket/blob/4.x-current/docs/generated/protocol.md#sourceaudioactivated
type SourceAudioActivatedEvent struct {
	// Source name.
	// Required: Yes.
	SourceName string `json:"sourceName,omitempty"`
	_event     `json:",squash"`
}

// SourceAudioSyncOffsetChangedEvent : The audio sync offset of a source has changed.
//
// Since obs-websocket version: 4.6.0.
//
// https://github.com/Palakis/obs-websocket/blob/4.x-current/docs/generated/protocol.md#sourceaudiosyncoffsetchanged
type SourceAudioSyncOffsetChangedEvent struct {
	// Source name.
	// Required: Yes.
	SourceName string `json:"sourceName,omitempty"`
	// Audio sync offset of the source (in nanoseconds).
	// Required: Yes.
	SyncOffset int `json:"syncOffset,omitempty"`
	_event     `json:",squash"`
}

// SourceAudioMixersChangedEvent : Audio mixer routing changed on a source.
//
// Since obs-websocket version: 4.6.0.
//
// https://github.com/Palakis/obs-websocket/blob/4.x-current/docs/generated/protocol.md#sourceaudiomixerschanged
type SourceAudioMixersChangedEvent struct {
	// Source name.
	// Required: Yes.
	SourceName string `json:"sourceName,omitempty"`
	// Routing status of the source for each audio mixer (array of 6 values).
	// Required: Yes.
	Mixers []map[string]interface{} `json:"mixers,omitempty"`
	// Mixer number.
	// Required: Yes.
	MixersID int `json:"mixers.*.id,omitempty"`
	// Routing status.
	// Required: Yes.
	MixersEnabled bool `json:"mixers.*.enabled,omitempty"`
	// Raw mixer flags (little-endian, one bit per mixer) as an hexadecimal value.
	// Required: Yes.
	HexMixersValue string `json:"hexMixersValue,omitempty"`
	_event         `json:",squash"`
}

// SourceRenamedEvent : A source has been renamed.
//
// Since obs-websocket version: 4.6.0.
//
// https://github.com/Palakis/obs-websocket/blob/4.x-current/docs/generated/protocol.md#sourcerenamed
type SourceRenamedEvent struct {
	// Previous source name.
	// Required: Yes.
	PreviousName string `json:"previousName,omitempty"`
	// New source name.
	// Required: Yes.
	NewName string `json:"newName,omitempty"`
	// Type of source (input, scene, filter, transition).
	// Required: Yes.
	SourceType string `json:"sourceType,omitempty"`
	_event     `json:",squash"`
}

// SourceFilterAddedEvent : A filter was added to a source.
//
// Since obs-websocket version: 4.6.0.
//
// https://github.com/Palakis/obs-websocket/blob/4.x-current/docs/generated/protocol.md#sourcefilteradded
type SourceFilterAddedEvent struct {
	// Source name.
	// Required: Yes.
	SourceName string `json:"sourceName,omitempty"`
	// Filter name.
	// Required: Yes.
	FilterName string `json:"filterName,omitempty"`
	// Filter type.
	// Required: Yes.
	FilterType string `json:"filterType,omitempty"`
	// Filter settings.
	// Required: Yes.
	FilterSettings map[string]interface{} `json:"filterSettings,omitempty"`
	_event         `json:",squash"`
}

// SourceFilterRemovedEvent : A filter was removed from a source.
//
// Since obs-websocket version: 4.6.0.
//
// https://github.com/Palakis/obs-websocket/blob/4.x-current/docs/generated/protocol.md#sourcefilterremoved
type SourceFilterRemovedEvent struct {
	// Source name.
	// Required: Yes.
	SourceName string `json:"sourceName,omitempty"`
	// Filter name.
	// Required: Yes.
	FilterName string `json:"filterName,omitempty"`
	// Filter type.
	// Required: Yes.
	FilterType string `json:"filterType,omitempty"`
	_event     `json:",squash"`
}

// SourceFilterVisibilityChangedEvent : The visibility/enabled state of a filter changed.
//
// Since obs-websocket version: 4.7.0.
//
// https://github.com/Palakis/obs-websocket/blob/4.x-current/docs/generated/protocol.md#sourcefiltervisibilitychanged
type SourceFilterVisibilityChangedEvent struct {
	// Source name.
	// Required: Yes.
	SourceName string `json:"sourceName,omitempty"`
	// Filter name.
	// Required: Yes.
	FilterName string `json:"filterName,omitempty"`
	// New filter state.
	// Required: Yes.
	FilterEnabled bool `json:"filterEnabled,omitempty"`
	_event        `json:",squash"`
}

// SourceFiltersReorderedEvent : Filters in a source have been reordered.
//
// Since obs-websocket version: 4.6.0.
//
// https://github.com/Palakis/obs-websocket/blob/4.x-current/docs/generated/protocol.md#sourcefiltersreordered
type SourceFiltersReorderedEvent struct {
	// Source name.
	// Required: Yes.
	SourceName string `json:"sourceName,omitempty"`
	// Ordered Filters list.
	// Required: Yes.
	Filters []map[string]interface{} `json:"filters,omitempty"`
	// Filter name.
	// Required: Yes.
	FiltersName string `json:"filters.*.name,omitempty"`
	// Filter type.
	// Required: Yes.
	FiltersType string `json:"filters.*.type,omitempty"`
	// Filter visibility status.
	// Required: Yes.
	FiltersEnabled bool `json:"filters.*.enabled,omitempty"`
	_event         `json:",squash"`
}
