// Code generated by protocol.py DO NOT EDIT
// Generator can be found at https://github.com/FlowingSPDG/go-obs-websocket/blob/master/codegen/protocol.py

package obsws

// VirtualCamStartedEvent : Virtual cam started successfully.
//
// Since obs-websocket version: 4.9.1.
//
// https://github.com/Palakis/obs-websocket/blob/4.x-current/docs/generated/protocol.md#virtualcamstarted
type VirtualCamStartedEvent struct {
	_event `json:",squash"`
}

// VirtualCamStoppedEvent : Virtual cam stopped successfully.
//
// Since obs-websocket version: 4.9.1.
//
// https://github.com/Palakis/obs-websocket/blob/4.x-current/docs/generated/protocol.md#virtualcamstopped
type VirtualCamStoppedEvent struct {
	_event `json:",squash"`
}
